language: node_js
node_js:
    - "4.3" # version used by AWS Lambda
    - "6.10" # next version used by AWS Lambda
    - "node"

install:
    - make install-sedy

script: make test

cache:
    directories:
        sedy/node_modules

branches:
  only:
    - master
